heatmap:
  grid_size: 30
  image_path: demo/output/frames
  min_count: 1
  true_axis: true
input_csv: demo/output/results.csv
output_dir: demo/output
plotxy:
  id_OR_class: class
  treatment_or_image_name: image_name
  true_axis: true
settings:
  filter_time_intervals: 16
  fps: 15
  interval_unit: minutes
  stat: mean
  time_intervals: 1
  treatment_or_image_name: treatment
  use_track_id: true
task:
  distance: true
  duration: true
  heatmap: false
  plotxy: true
  visits: true
